# Generated by Django 5.0.7 on 2024-12-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llm_name', models.CharField(max_length=255, unique=True)),
                ('is_downloaded', models.BooleanField(default=False)),
            ],
        ),
    ]
